### PR TITLE
Add sites.all() to list all sites for a given query

### PR DESCRIPTION
**Pull request by joshbetz**

### CODE REVIEW

**Comment by joshbetz** [comment]
I guess there's not wide browser support for the spread (...) operator, so we may need to replace that.

**Comment by joshbetz** [comment]
There are a couple problems with this:

1. We create 1 request per page essentially all at the same time -- could hit a rate limit pretty easily.
2. We buffer all the results in RAM simultaneously.

It would be better to use something like generators and lazy-load the next page of results. I'm going to leave this PR for now and we can revisit later.

**Comment by mjangda** [comment]
> not wide browser support for the spread (...) operator

babel + webpack?

**Comment by chrean** [comment]
Closing as I don't think this is a priority and it's 3 years old.

**Pull request closed without merging**
